function getVokabeln(){
    let vokabeln = {
        aufwachen: {grundform: "wake up", simplePast: "woke up"},
        "denken, glauben": {grundform: "think", simplePast: "thought"},
        "machen; herstellen": {grundform: "make", simplePast: "made"},
        "nehmen; bringen": {grundform: "take", simplePast: "took"},
        sagen: {grundform: "say", simplePast: "said"},
        schwimmen: {grundform: "swim", simplePast: "swam"},
        sehen: {grundform: "see", simplePast: "saw"},
        "sitzen; sich setzen": {grundform: "sit", simplePast: "sat"},
        schreiben: {grundform: "write", simplePast: "wrote"},
        "wissen; kennen": {grundform: "know", simplePast: "knew"},
        "laufen, rennen": {grundform: "run", simplePast: "ran"},
        "schicken, senden": {grundform: "send", simplePast: "sent"},
        singen: {grundform: "sing", simplePast: "sang"},
        gewinnen: {grundform: "win", simplePast: "won"},
        "(sich) treffen": {grundform: "meet", simplePast: "met"},
        "legen, stellen": {grundform: "put", simplePast: "put"},
        lesen: {grundform: "read", simplePast: "read"},
        "erzählen, berichten": {grundform: "tell", simplePast: "told"},
        "Rad fahren": {grundform: "ride a bike", simplePast: "rode a bike"},
        verkaufen: {grundform: "sell", simplePast: "sold"},
        sprechen: {grundform: "speak", simplePast: "spoke"},
        verstehen: {grundform: "understand", simplePast: "understood"},
        "tragen (Kleidung)": {grundform: "wear", simplePast: "wore"},
        
        //A,B,C,...
        sein: {grundform: "be", simplePast: "was, were"},
        werden: {grundform: "become", simplePast: "became"},
        "beginnen, anfangen": {grundform: "begin", simplePast: "began"},
        beißen: {grundform: "bite", simplePast: "bit"},
        "etwas auspusten, ausblasen": {grundform: "blow sth. out", simplePast: "blew"},
        "brechen; zerbrechen": {grundform: "break", simplePast: "broke"},
        bringen: {grundform: "bring", simplePast: "brought"},
        bauen: {grundform: "build", simplePast: "build"},
        kaufen: {grundform: "buy", simplePast: "bought"},
        fangen: {grundform: "catch", simplePast: "caught"},
        "aussuchen, (aus)wählen": {grundform: "choose", simplePast: "chose"},
        kommen: {grundform: "come", simplePast: "came"},
        kosten: {grundform: "cost", simplePast: "cost"},
        schneiden: {grundform: "cut", simplePast: "cut"},
        "tun, machen": {grundform: "do", simplePast: "did"},
        zeichnen: {grundform: "draw", simplePast: "drew"},
        "(mit dem Auto) fahren": {grundform: "drive", simplePast: "drove"},
        trinken: {grundform: "drink", simplePast: "drank"},
        essen: {grundform: "eat", simplePast: "ate"},
        fallen: {grundform: "fall", simplePast: "fell"},
        füttern: {grundform: "feed", simplePast: "fed"},
        "fühlen; sich fühlen": {grundform: "feel", simplePast: "felt"},
        "(be)kämpfen": {grundform: "fight", simplePast: "fought"},
        finden: {grundform: "find", simplePast: "found"},
        fliegen: {grundform: "fly", simplePast: "flew"},
        vergessen: {grundform: "forget", simplePast: "forgot"},
        "bekommen; werden; gelangen, (hin)kommen": {grundform: "get", simplePast: "got"},
        geben: {grundform: "give", simplePast: "gave"},
        gehen: {grundform: "go", simplePast: "went"},
        "anbauen, anpflanzen": {grundform: "grow", simplePast: "grew"},
        hängen: {grundform: "hang", simplePast: "hung"},
        haben: {grundform: "have", simplePast: "had"},
        hören: {grundform: "hear", simplePast: "haerd"},
        "verstecken; sich verstecken": {grundform: "hide", simplePast: "hid"},
        schlagen: {grundform: "hit", simplePast: "hit"},
        halten: {grundform: "hold", simplePast: "held"},
        "schmerzen, wehtun; verletzen": {grundform: "hurt", simplePast: "hurt"},
        "verlassen; zutücklassen" : {grundform: "leave", simplePast: "left"},
        lassen: {grundform: "let", simplePast: "let"},
        liegen: {grundform: "lie", simplePast: "lay"},
        : {grundform: "", simplePast: ""},
        : {grundform: "", simplePast: ""},
        : {grundform: "", simplePast: ""},
        : {grundform: "", simplePast: ""},
        : {grundform: "", simplePast: ""},
        : {grundform: "", simplePast: ""},
        : {grundform: "", simplePast: ""},
        // : {grundform: "", simplePast: ""},
    };
    
    return vokabeln;
}