function getVokabeln(){
    let vokabeln = {

        //A,B,C,...
        sein: {grundform: "be", simplePast: "was, were"},
        werden: {grundform: "become", simplePast: "became"},
        "beginnen, anfangen": {grundform: "begin", simplePast: "began"},
        beißen: {grundform: "bite", simplePast: "bit"},
        "etwas auspusten, ausblasen": {grundform: "blow sth. out", simplePast: "blew"},
        "brechen; zerbrechen": {grundform: "break", simplePast: "broke"},
        bringen: {grundform: "bring", simplePast: "brought"},
        bauen: {grundform: "build", simplePast: "built"},
        kaufen: {grundform: "buy", simplePast: "bought"},
        fangen: {grundform: "catch", simplePast: "caught"},
        "aussuchen, (aus)wählen": {grundform: "choose", simplePast: "chose"},
        kommen: {grundform: "come", simplePast: "came"},
        kosten: {grundform: "cost", simplePast: "cost"},
        schneiden: {grundform: "cut", simplePast: "cut"},
        "tun, machen": {grundform: "do", simplePast: "did"},
        zeichnen: {grundform: "draw", simplePast: "drew"},
        "(mit dem Auto) fahren": {grundform: "drive", simplePast: "drove"},
        trinken: {grundform: "drink", simplePast: "drank"},
        essen: {grundform: "eat", simplePast: "ate"},
        fallen: {grundform: "fall", simplePast: "fell"},
        füttern: {grundform: "feed", simplePast: "fed"},
        "fühlen; sich fühlen": {grundform: "feel", simplePast: "felt"},
        "(be)kämpfen": {grundform: "fight", simplePast: "fought"},
        finden: {grundform: "find", simplePast: "found"},
        fliegen: {grundform: "fly", simplePast: "flew"},
        vergessen: {grundform: "forget", simplePast: "forgot"},
        "bekommen; werden; gelangen, (hin)kommen": {grundform: "get", simplePast: "got"},
        geben: {grundform: "give", simplePast: "gave"},
        gehen: {grundform: "go", simplePast: "went"},
        "anbauen, anpflanzen": {grundform: "grow", simplePast: "grew"},
        hängen: {grundform: "hang", simplePast: "hung"},
        haben: {grundform: "have", simplePast: "had"},
        hören: {grundform: "hear", simplePast: "heard"},
        "verstecken; sich verstecken": {grundform: "hide", simplePast: "hid"},
        schlagen: {grundform: "hit", simplePast: "hit"},
        halten: {grundform: "hold", simplePast: "held"},
        "schmerzen, wehtun; verletzen": {grundform: "hurt", simplePast: "hurt"},
        "wissen; kennen": {grundform: "know", simplePast: "knew"},
        "verlassen; zurücklassen" : {grundform: "leave", simplePast: "left"},
        lassen: {grundform: "let", simplePast: "let"},
        liegen: {grundform: "lie", simplePast: "lay"},
        anzünden: {grundform: "light", simplePast: "lit"},
        verlieren: {grundform: "lose", simplePast: "lost"},
        "machen; herstellen": {grundform: "make", simplePast: "made"},
        "bedeuten; meinen": {grundform: "mean", simplePast: "meant"},
        "(sich) treffen": {grundform: "meet", simplePast: "met"},
        bezahlen: {grundform: "pay", simplePast: "paid"},
        "legen, tun, stellen": {grundform: "put", simplePast: "put"},
        lesen: {grundform: "read", simplePast: "read"},
        "reiten; (Rad) fahren": {grundform: "ride", simplePast: "rode"},
        "klingeln, läuten": {grundform: "ring", simplePast: "rang"},
        "laufen, rennen": {grundform: "run", simplePast: "ran"},
        sagen: {grundform: "say", simplePast: "said"},
        sehen: {grundform: "see", simplePast: "saw"},
        verkaufen: {grundform: "sell", simplePast: "sold"},
        "schicken, senden": {grundform: "send", simplePast: "sent"},
        schütteln: {grundform: "shake", simplePast: "shook"},
        singen: {grundform: "sing", simplePast: "sang"},
        "sitzen; sich setzen": {grundform: "sit", simplePast: "sat"},
        schlafen: {grundform: "sleep", simplePast: "slept"},
        sprechen: {grundform: "speak", simplePast: "spoke"},
        "stehen; sich (hin)stellen": {grundform: "stand", simplePast: "stood"},
        "stechen, stecken": {grundform: "stick", simplePast: "stuck"},
        schwimmen: {grundform: "swim", simplePast: "swam"},
        "nehmen; bringen": {grundform: "take", simplePast: "took"},
        "erzählen, berichten": {grundform: "tell", simplePast: "told"},
        "denken, glauben": {grundform: "think", simplePast: "thought"},
        werfen: {grundform: "throw", simplePast: "threw"},
        verstehen: {grundform: "understand", simplePast: "understood"},
        aufwachen: {grundform: "wake up", simplePast: "woke up"},
        "tragen (Kleidung)": {grundform: "wear", simplePast: "wore"},
        gewinnen: {grundform: "win", simplePast: "won"},
        schreiben: {grundform: "write", simplePast: "wrote"},
        // : {grundform: "", simplePast: ""},
    };

    return vokabeln;
}