function getVokabeln(){
    let vokabeln = {
        gehen: {grundform: "go", simplePast: "went"},
        bringen: {grundform: "bring", simplePast: "brought"},
        fangen: {grundform: "catch", simplePast: "caught"},
        "aussuchen, (aus)wählen": {grundform: "choose", simplePast: "chose"},
        "machen; herstellen": {grundform: "make", simplePast: "made"},
        sagen: {grundform: "say", simplePast: "said"},
        sehen: {grundform: "see", simplePast: "saw"},
        "sitzen; sich setzen": {grundform: "sit", simplePast: "sat"},
        schwimmen: {grundform: "swim", simplePast: "swam"},
        "nehmen; bringen": {grundform: "take", simplePast: "took"},
        "denken, glauben": {grundform: "think", simplePast: "thought"},
        schreiben: {grundform: "write", simplePast: "wrote"},
        kommen: {grundform: "come", simplePast: "came"},
        "tun, machen": {grundform: "do", simplePast: "did"},
        fallen: {grundform: "fall", simplePast: "fell"},
        "fühlen; sich fühlen": {grundform: "feel", simplePast: "felt"},
        "bekommen; werden; gelangen, (hin)kommen": {grundform: "get", simplePast: "got"},
        haben: {grundform: "have", simplePast: "had"},
        "wissen; kennen": {grundform: "know", simplePast: "knew"},
       "verlassen; zutücklassen" : {grundform: "leave", simplePast: "left"},
        "laufen, rennen": {grundform: "run", simplePast: "ran"},
        "schicken, senden": {grundform: "send", simplePast: "sent"},
        singen: {grundform: "sing", simplePast: "sang"},
        gewinnen: {grundform: "win", simplePast: "won"},
        finden: {grundform: "find", simplePast: "found"},
        geben: {grundform: "give", simplePast: "gave"},
        "anbauen, anpflanzen": {grundform: "grow", simplePast: "grew"},
        halten: {grundform: "hold", simplePast: "held"},
        "(sich) treffen": {grundform: "meet", simplePast: "met"},
        "legen, stellen": {grundform: "put", simplePast: "put"},
        lesen: {grundform: "read", simplePast: "read"},
        "erzählen, berichten": {grundform: "tell", simplePast: "told"},
        // : {grundform: "", simplePast: ""},
    };

    return vokabeln;
}