function getVokabeln(){
    let vokabeln = {

        //A,B,C,...
        sein: {grundform: "be", simplepast: "was, were"},
        werden: {grundform: "become", simplepast: "became"},
        "beginnen, anfangen": {grundform: "begin", simplepast: "began"},
        beißen: {grundform: "bite", simplepast: "bit"},
        "etwas auspusten, ausblasen": {grundform: "blow", simplepast: "blew"},
        "brechen; zerbrechen": {grundform: "break", simplepast: "broke"},
        bringen: {grundform: "bring", simplepast: "brought"},
        bauen: {grundform: "build", simplepast: "built"},
        kaufen: {grundform: "buy", simplepast: "bought"},
        fangen: {grundform: "catch", simplepast: "caught"},
        "aussuchen, (aus)wählen": {grundform: "choose", simplepast: "chose"},
        kommen: {grundform: "come", simplepast: "came"},
/*        kosten: {grundform: "cost", simplepast: "cost"},
        schneiden: {grundform: "cut", simplepast: "cut"},
        "tun, machen": {grundform: "do", simplepast: "did"},
        zeichnen: {grundform: "draw", simplepast: "drew"},
        "(mit dem Auto) fahren": {grundform: "drive", simplepast: "drove"},
        trinken: {grundform: "drink", simplepast: "drank"},
        essen: {grundform: "eat", simplepast: "ate"},
        fallen: {grundform: "fall", simplepast: "fell"},
        füttern: {grundform: "feed", simplepast: "fed"},
        "fühlen; sich fühlen": {grundform: "feel", simplepast: "felt"},
        "(be)kämpfen": {grundform: "fight", simplepast: "fought"},
        finden: {grundform: "find", simplepast: "found"},
        fliegen: {grundform: "fly", simplepast: "flew"},
        vergessen: {grundform: "forget", simplepast: "forgot"},
        "bekommen; werden; gelangen, (hin)kommen": {grundform: "get", simplepast: "got"},
        geben: {grundform: "give", simplepast: "gave"},
        gehen: {grundform: "go", simplepast: "went"},
        "anbauen, anpflanzen": {grundform: "grow", simplepast: "grew"},
        hängen: {grundform: "hang", simplepast: "hung"},
        haben: {grundform: "have", simplepast: "had"},
        hören: {grundform: "hear", simplepast: "heard"},
        "verstecken; sich verstecken": {grundform: "hide", simplepast: "hid"},
        schlagen: {grundform: "hit", simplepast: "hit"},
        halten: {grundform: "hold", simplepast: "held"},
        "schmerzen, wehtun; verletzen": {grundform: "hurt", simplepast: "hurt"},
        "wissen; kennen": {grundform: "know", simplepast: "knew"},
        "verlassen; zurücklassen" : {grundform: "leave", simplepast: "left"},
        lassen: {grundform: "let", simplepast: "let"},
        liegen: {grundform: "lie", simplepast: "lay"},
        anzünden: {grundform: "light", simplepast: "lit"},
        verlieren: {grundform: "lose", simplepast: "lost"},
        "machen; herstellen": {grundform: "make", simplepast: "made"},
        "bedeuten; meinen": {grundform: "mean", simplepast: "meant"},
        "(sich) treffen": {grundform: "meet", simplepast: "met"},
        bezahlen: {grundform: "pay", simplepast: "paid"},
        "legen, tun, stellen": {grundform: "put", simplepast: "put"},
        lesen: {grundform: "read", simplepast: "read"},
        "reiten; (Rad) fahren": {grundform: "ride", simplepast: "rode"},
        "klingeln, läuten": {grundform: "ring", simplepast: "rang"},
        "laufen, rennen": {grundform: "run", simplepast: "ran"},
        sagen: {grundform: "say", simplepast: "said"},
        sehen: {grundform: "see", simplepast: "saw"},
        verkaufen: {grundform: "sell", simplepast: "sold"},
        "schicken, senden": {grundform: "send", simplepast: "sent"},
        schütteln: {grundform: "shake", simplepast: "shook"},
        singen: {grundform: "sing", simplepast: "sang"},
        "sitzen; sich setzen": {grundform: "sit", simplepast: "sat"},
        schlafen: {grundform: "sleep", simplepast: "slept"},
        sprechen: {grundform: "speak", simplepast: "spoke"},
        "stehen; sich (hin)stellen": {grundform: "stand", simplepast: "stood"},
        "stechen, stecken": {grundform: "stick", simplepast: "stuck"},
        schwimmen: {grundform: "swim", simplepast: "swam"},
        "nehmen; bringen": {grundform: "take", simplepast: "took"},
        "erzählen, berichten": {grundform: "tell", simplepast: "told"},
        "denken, glauben": {grundform: "think", simplepast: "thought"},
        werfen: {grundform: "throw", simplepast: "threw"},
        verstehen: {grundform: "understand", simplepast: "understood"},
        aufwachen: {grundform: "wake up", simplepast: "woke up"},
        "tragen (Kleidung)": {grundform: "wear", simplepast: "wore"},
        gewinnen: {grundform: "win", simplepast: "won"},
        schreiben: {grundform: "write", simplepast: "wrote"},
        // : {grundform: "", simplepast: ""},*/
    };

    return vokabeln;
}