function getVokabeln(){
    let vokabeln = {
        //A,B,C,...
        sein: {grundform: "be", simplepast: "was, were", perfect: "been"},
        werden: {grundform: "become", simplepast: "became", perfect: "become"},
        "beginnen, anfangen": {grundform: "begin", simplepast: "began", perfect: "begun"},
        beißen: {grundform: "bite", simplepast: "bit", perfect: "bitten"},
        "etwas auspusten, ausblasen": {grundform: "blow", simplepast: "blew", perfect: "blown"},
        "brechen; zerbrechen": {grundform: "break", simplepast: "broke", perfect: "broken"},
        bringen: {grundform: "bring", simplepast: "brought", perfect: "brought"},
        bauen: {grundform: "build", simplepast: "built", perfect: "built"},
        kaufen: {grundform: "buy", simplepast: "bought", perfect: "bought"},
        fangen: {grundform: "catch", simplepast: "caught", perfect: "caught"},
        "aussuchen, (aus)wählen": {grundform: "choose", simplepast: "chose", perfect: "chosen"},
        kommen: {grundform: "come", simplepast: "came", perfect: "come"},
        kosten: {grundform: "cost", simplepast: "cost", perfect: "cost"},
        schneiden: {grundform: "cut", simplepast: "cut", perfect: "cut"},
        "tun, machen": {grundform: "do", simplepast: "did", perfect: "done"},
        zeichnen: {grundform: "draw", simplepast: "drew", perfect: "drawn"},
        "(mit dem Auto) fahren": {grundform: "drive", simplepast: "drove", perfect: "driven"},
        trinken: {grundform: "drink", simplepast: "drank", perfect: "drunk"},
        essen: {grundform: "eat", simplepast: "ate", perfect: "eaten"},
        fallen: {grundform: "fall", simplepast: "fell", perfect: "fallen"},
        füttern: {grundform: "feed", simplepast: "fed", perfect: "fed"},
        "fühlen; sich fühlen": {grundform: "feel", simplepast: "felt", perfect: "felt"},
        "(be)kämpfen": {grundform: "fight", simplepast: "fought", perfect: "fought"},
        finden: {grundform: "find", simplepast: "found", perfect: "found"},
        fliegen: {grundform: "fly", simplepast: "flew", perfect: "flown"},
        vergessen: {grundform: "forget", simplepast: "forgot", perfect: "forgotten"},
        "bekommen; werden; gelangen, (hin)kommen": {grundform: "get", simplepast: "got", perfect: "got"},
        geben: {grundform: "give", simplepast: "gave", perfect: "given"},
        gehen: {grundform: "go", simplepast: "went", perfect: "gone"},
        "anbauen, anpflanzen": {grundform: "grow", simplepast: "grew", perfect: "grown"},
        hängen: {grundform: "hang", simplepast: "hung", perfect: "hung"},
        haben: {grundform: "have", simplepast: "had", perfect: "had"},
        hören: {grundform: "hear", simplepast: "heard", perfect: "heard"},
        "verstecken; sich verstecken": {grundform: "hide", simplepast: "hid", perfect: "hidden"},
        schlagen: {grundform: "hit", simplepast: "hit", perfect: "hit"},
        halten: {grundform: "hold", simplepast: "held", perfect: "held"},
        "schmerzen, wehtun; verletzen": {grundform: "hurt", simplepast: "hurt", perfect: "hurt"},
        "wissen; kennen": {grundform: "know", simplepast: "knew", perfect: "known"},
        "verlassen; zurücklassen" : {grundform: "leave", simplepast: "left", perfect: "left"},
        lassen: {grundform: "let", simplepast: "let", perfect: "let"},
        liegen: {grundform: "lie", simplepast: "lay", perfect: "lain"},
        anzünden: {grundform: "light", simplepast: "lit", perfect: ""},
        verlieren: {grundform: "lose", simplepast: "lost", perfect: ""},
        "machen; herstellen": {grundform: "make", simplepast: "made", perfect: ""},
        "bedeuten; meinen": {grundform: "mean", simplepast: "meant", perfect: ""},
        "(sich) treffen": {grundform: "meet", simplepast: "met", perfect: ""},
        bezahlen: {grundform: "pay", simplepast: "paid", perfect: ""},
        "legen, tun, stellen": {grundform: "put", simplepast: "put", perfect: ""},
        lesen: {grundform: "read", simplepast: "read", perfect: ""},
        "reiten; (Rad) fahren": {grundform: "ride", simplepast: "rode", perfect: ""},
        "klingeln, läuten": {grundform: "ring", simplepast: "rang", perfect: ""},
        "laufen, rennen": {grundform: "run", simplepast: "ran", perfect: ""},
        sagen: {grundform: "say", simplepast: "said", perfect: ""},
        sehen: {grundform: "see", simplepast: "saw", perfect: ""},
        verkaufen: {grundform: "sell", simplepast: "sold", perfect: ""},
        "schicken, senden": {grundform: "send", simplepast: "sent", perfect: ""},
        schütteln: {grundform: "shake", simplepast: "shook", perfect: ""},
        singen: {grundform: "sing", simplepast: "sang", perfect: ""},
        "sitzen; sich setzen": {grundform: "sit", simplepast: "sat", perfect: ""},
        schlafen: {grundform: "sleep", simplepast: "slept", perfect: ""},
        sprechen: {grundform: "speak", simplepast: "spoke", perfect: ""},
        "stehen; sich (hin)stellen": {grundform: "stand", simplepast: "stood", perfect: ""},
        "stechen, stecken": {grundform: "stick", simplepast: "stuck", perfect: ""},
        schwimmen: {grundform: "swim", simplepast: "swam", perfect: ""},
        "nehmen; bringen": {grundform: "take", simplepast: "took", perfect: ""},
        "erzählen, berichten": {grundform: "tell", simplepast: "told", perfect: ""},
        "denken, glauben": {grundform: "think", simplepast: "thought", perfect: ""},
        werfen: {grundform: "throw", simplepast: "threw", perfect: ""},
        verstehen: {grundform: "understand", simplepast: "understood", perfect: ""},
        aufwachen: {grundform: "wake up", simplepast: "woke up", perfect: ""},
        "tragen (Kleidung)": {grundform: "wear", simplepast: "wore", perfect: ""},
        gewinnen: {grundform: "win", simplepast: "won", perfect: ""},
        schreiben: {grundform: "write", simplepast: "wrote", perfect: ""},
        // : {grundform: "", simplepast: "", perfect: ""},
    };

    return vokabeln;
}